gestion_conges_stats/src/Entity/Conge.php
<?php

namespace App\Entity;

use App\Repository\CongeRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;

#[ORM\Entity(repositoryClass: CongeRepository::class)]
class Conge
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $type = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $statut = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

gestion_conges_stats/src/Controller/CongeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\CongeRepository;
use App\Entity\Conge;

class CongeController extends AbstractController
{
    private $congeRepository;

    public function __construct(CongeRepository $congeRepository)
    {
        $this->congeRepository = $congeRepository;
    }

    #[Route('/conge', name: 'conge')]
    public function index(): Response
    {
        // Utiliser la méthode findAll() pour récupérer tous les congés
        $userConges = $this->congeRepository->findAll();

        // Passer les congés à la vue
        return $this->render('conge/index.html.twig', [
            'userConges' => $userConges,
        ]);
    }
   
}

gestion_conges_stats/templates/conge/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des congés{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="text-center mb-4">Liste des congés</h1>

    {% if userConges is not empty %}
        <div class="card mb-3">
            <div class="card-body p-0">
                <ul class="list-group list-group-flush">
                    {% for conge in userConges %}
                        <li class="list-group-item">
                            <strong>Utilisateur:</strong> {{ conge.user.nom }} {{ conge.user.prenom }}<br>
                            <strong>Type:</strong> {{ conge.type }}<br>
                            <strong>Date de début:</strong> {{ conge.dateDebut|date('d/m/Y') }}<br>
                            <strong>Date de fin:</strong> {{ conge.dateFin|date('d/m/Y') }}<br>
                            <strong>Statut:</strong> {{ conge.statut }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% else %}
        <div class="alert alert-warning text-center" role="alert">
            Aucun congé trouvé.
        </div>
    {% endif %}
</div>
{% endblock %}